# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todoey' do

  # Pods for Todoey
  
  pod 'Realm', :modular_headers => true
  pod 'RealmSwift', :modular_headers => true
  pod 'SwipeCellKit'
  
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

end
